FROM ubuntu:18.04
LABEL maintainer="Conrad Taylor <conradwt@gmail.com>"

ENV LANG=C.UTF-8 LC_ALL=C.UTF-8

RUN apt-get update -qq -y
RUN apt-get install -qq -y curl gnupg
RUN curl -sL https://deb.nodesource.com/setup_10.x | bash -
# RUN curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
# RUN echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee \ /etc/apt/sources.list.d/yarn.list

RUN apt-get update -y && apt-get install -qq -y --no-install-recommends \
  autoconf \
  bash \
  bash-completion \
  bison \
  build-essential \
  ctags \
  git-core \
  imagemagick \
  libcurl3-dev \
  libffi-dev \
  libgdbm-dev \
  libgdbm5 \
  libmagick++-6-headers \
  libncurses5-dev \
  libpq-dev \
  libreadline6-dev \
  libssl-dev \
  libssl1.0-dev \
  libyaml-dev \
  locales \
  nodejs \
  postgresql-10 \ 
  postgresql-client-10 \
  snapd \
  unzip \
  yarn \
  zlib1g-dev

RUN service postgresql start

RUN useradd -m -s /bin/bash -G sudo ruser
RUN echo "ruser:ruser" | chpasswd
USER pyuser
WORKDIR /home/ruser
# RUN chsh -s /bin/bash

# RUN \
#   cd $HOME && \
#   git clone https://github.com/conradwt/rails-setup-guide-for-ubuntu && \
#   cd rails-setup-guide-for-ubuntu && \
#   git clone https://github.com/sstephenson/rbenv.git ~/.rbenv && \
#   cd ~/.rbenv && src/configure && make -C src && \
#   echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bashrc && \
#   echo 'eval "$(rbenv init -)"' >> ~/.bashrc && \
#   source $HOME/.bashrc && \
#   cd $HOME/rails-setup-guide-for-ubuntu && \
#   chmod +x install-rbenv-plugins.sh && \
#   ./install-rbenv-plugins.sh

CMD [ "/bin/bash" ]
